version: "3.3"
services:

  rtsp-capture-1:
    image: restreamio/gstreamer:1.18.4.0-prod
    env_file: .env
    volumes: 
      - /mnt/ramdisk:/input
    command: gst-launch-1.0 rtspsrc location=$RTSP_URL latency=200 ! queue ! rtph264depay ! avdec_h264 ! videorate ! video/x-raw,framerate=1000/1001 ! jpegenc ! multifilesink location="./input/frame%020d.jpg"

  yolo-object-detection:
    build: .
    env_file: .env
    networks: 
      camera-stream-network:
    volumes: 
    - ./output:/app/output
    - /mnt/ramdisk:/app/input
    command: python3 yolo_od.py
    restart: unless-stopped
    depends_on: 
      - rtsp-capture-1
    #deploy:
    #    resources:
    #        limits:
    #          cpus: '3'
    #          memory: 512M

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Africa/Johannesburg
      - PORT=2880
      - AUTHORIZED_TELEGRAM_CLIENTS=${AUTHORIZED_TELEGRAM_CLIENTS}
    network_mode: host
    volumes:
      - ./node-red-data:/data
      - ./output:/detected
      - /mnt/ramdisk:/live
    restart: unless-stopped
    depends_on:
      - yolo-object-detection

networks:
  camera-stream-network:
    driver: bridge