version: "3.3"
services:

  rtsp-capture-husky:
    image: restreamio/gstreamer:1.18.4.0-prod
    env_file: husky.env
    volumes: 
      - ./input:/input
      - ./getframesfromRTSP.sh:/getframesfromRTSP.sh
    command: bash getframesfromRTSP.sh
    restart: unless-stopped

  yolo-object-detection:
    build: .
    volumes: 
    - ./output:/app/output
    - ./input:/app/input
    command: python3 yolo_od.py
    restart: unless-stopped
    depends_on: 
      - rtsp-capture-husky
    deploy:
       resources:
           limits:
             cpus: '3'
             memory: 512M

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Africa/Johannesburg
      - PORT=2880
      - AUTHORIZED_TELEGRAM_CLIENTS=${AUTHORIZED_TELEGRAM_CLIENTS}
    network_mode: host
    volumes:
      - ./node-red-data:/data
      - ./output:/detected
      - ./input:/live
    restart: unless-stopped
    depends_on:
      - yolo-object-detection